name: Microblocks
version: 1.9
description: Extra building blocks!
author: itsCrafted

main: net.itscrafted.microblocks.Microblocks
 
commands:
  microblocks:
    description: Spawn microblocks.
    aliases: [mb, miniblocks, micro]
  skull:
    description: Spawn a player skull.
    aliases: [head, playerhead, ph]
  givemb:
    description: Give another player a Microblock.
    aliases: [gmb, mbgive, givemicroblock]