name: Microblocks
version: 1.7
description: Extra building blocks!
author: itsCrafted

main: net.itscrafted.microblocks.Microblocks
 
commands:
  microblocks:
    description: Spawn microblocks.
    aliases: [mb, miniblocks]
  skull:
    description: Spawn a player skull.
    aliases: [head, playerhead, ph]
